# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2022-2023 Dyne.org foundation <foundation@dyne.org>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# playbook.yml
---

- name: Deploy replicasets
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Create config directory
      file:
        path: /etc/tarantool/conf.d
        state: directory

    - name: 'Get repository setup script'
      get_url:
        url: 'https://tarantool.io/release/2/installer.sh'
        dest: '/tmp/tarantool-installer.sh'

    - name: 'Run repository setup script'
      any_errors_fatal: true
      command: bash /tmp/tarantool-installer.sh
      changed_when: false

    # - apt:
    #     upgrade: 'yes'
    #     update_cache: yes
    #     cache_valid_time: 86400
    #   ignore_errors: yes

    - name: Install dependencies
      package:
        name:
          - tarantool
        state: latest
    - name: Download the package
      shell: |
        curl https://github.com/dyne/zenswarm-storage/releases/download/v1.0.0/zenswarm-storage-1.0.0-0.deb


- name: Deploy my Tarantool Cartridge app
  become: true
  hosts: all
  become_user: root
  any_errors_fatal: true
  gather_facts: false
  roles:
    - tarantool.cartridge
  vars:
    cartridge_scenario:
      - cleanup
      - deliver_package
      - update_package
      - configure_instance
      - configure_app_config
      - restart_instance
      - wait_instance_started
      - bootstrap_vshard
