---
all:
  vars:
    cartridge_app_name: zenswarm-storage
    cartridge_package_path: ../zenswarm-storage_1.0.0-1_all.deb
    delivered_package_path: /root/
    cartridge_cluster_cookie: secret-cookie
    cartridge_bootstrap_vshard: true
    cartridge_app_user: root
    cartridge_app_group: root
    cartridge_enable_tarantool_repo: false

  hosts:
    router:
      config:
        advertise_uri: '65.109.138.188:3301'
        http_port: 8081

    s1-master:
      config:
        advertise_uri: '65.109.138.188:3302'
        http_port: 8082

    s1-replica:
      config:
        advertise_uri: '65.109.162.224:3303'
        http_port: 8083

  children:
    tt1:
      vars:
        ansible_host: 65.109.138.188
        ansible_user: root

      hosts:
        router:
        s1-master:

    tt2:
      vars:
        ansible_host: 65.109.162.224
        ansible_user: root

      hosts:
        s1-replica:

    router_rs:
      hosts:
        router:
      vars:
        replicaset_alias: router
        roles:
          - vshard-router
          - failover-coordinator
          - app.roles.zenswarm-router

    s_1:
      hosts:
        s1-master:
        s1-replica:
      vars:
        replicaset_alias: s_1
        roles:
          - vshard-storage
          - app.roles.zenswarm-storage
        failover_priority:
          - s1-master
          - s1-replica
