# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2022-2023 Dyne.org foundation <foundation@dyne.org>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
all:
  vars:
    cartridge_app_name: zenswarm-storage
    cartridge_package_path: ../zenswarm-storage-1.0.0-0.deb
    delivered_package_path: /root/
    cartridge_cluster_cookie: secret-cookie
    cartridge_bootstrap_vshard: true
    cartridge_app_user: root
    cartridge_app_group: root
    cartridge_enable_tarantool_repo: false

  hosts:
    router:
      config:
        advertise_uri: '194.195.242.218:3301'
        http_port: 8081

    s1-master:
      config:
        advertise_uri: '194.195.242.218:3302'
        http_port: 8082

    s1-replica:
      config:
        advertise_uri: '172.105.244.39:3303'
        http_port: 8083

  children:
    tt1:
      vars:
        ansible_host: 194.195.242.218
        ansible_user: root

      hosts:
        router:
        s1-master:

    tt2:
      vars:
        ansible_host: 172.105.244.39
        ansible_user: root

      hosts:
        s1-replica:

    router-rs:
      hosts:
        router:
      vars:
        replicaset_alias: router
        roles:
          - vshard-router
          - failover-coordinator
          - app.roles.zenswarm-router

    s-1:
      hosts:
        s1-master:
        s1-replica:
      vars:
        replicaset_alias: s-1
        roles:
          - vshard-storage
          - app.roles.zenswarm-storage
        failover_priority:
          - s1-master
          - s1-replica
